/**
 * Biblioteca de ejercicios.
 *
 * Datos puros: sin React, sin red, sin estado. Todas las cadenas visibles son
 * claves i18n; aquí no se escribe nunca texto para el usuario final.
 *
 * Convención de claves:
 *   nombre       -> `exercise.<slug_snake>`
 *   instrucción  -> `exercise.<slug_snake>.cue.<token>`
 *   error común  -> `exercise.<slug_snake>.mistake.<token>`
 *   nota segura  -> `exercise.<slug_snake>.safety.<token>`
 *
 * El campo `equipment` lista TODO el material necesario: un ejercicio solo se
 * puede hacer si el usuario dispone de todos esos elementos. `['none']`
 * significa que no hace falta nada (entreno en casa).
 */

import type {
  Difficulty,
  Equipment,
  Exercise,
  MovementPattern,
  MuscleGroup,
} from '@/types/domain';

const toSnake = (slug: string): string => slug.replace(/-/g, '_');

/**
 * Construye un ejercicio a partir de datos posicionales.
 * Orden: slug, patrón, músculos primarios, secundarios, equipo, dificultad,
 * instrucciones, errores comunes, notas de seguridad, alternativas.
 */
function s(
  slug: string,
  pattern: MovementPattern,
  primary: MuscleGroup[],
  secondary: MuscleGroup[],
  equipment: Equipment[],
  difficulty: Difficulty,
  cues: string[],
  mistakes: string[],
  safety: string[],
  alternatives: string[],
): Exercise {
  const base = `exercise.${toSnake(slug)}`;
  return {
    id: slug,
    slug,
    nameKey: base,
    pattern,
    primaryMuscles: primary,
    secondaryMuscles: secondary,
    equipment,
    difficulty,
    instructionKeys: cues.map((c) => `${base}.cue.${c}`),
    commonMistakeKeys: mistakes.map((m) => `${base}.mistake.${m}`),
    safetyNoteKeys: safety.map((n) => `${base}.safety.${n}`),
    alternatives,
  };
}

/** Catálogo completo. El orden es estable: los generadores dependen de él. */
export const EXERCISES: Exercise[] = [
  /* ------------------------------------------------------------- sentadilla */
  s('barbell-back-squat', 'squat', ['quads', 'glutes'], ['hamstrings', 'lower_back', 'abs'], ['barbell', 'plates', 'rack'], 'intermediate',
    ['brace_core', 'sit_between_hips', 'drive_midfoot'], ['knees_cave_in', 'heels_lift'], ['set_safety_bars'],
    ['goblet-squat', 'leg-press', 'dumbbell-squat']),
  s('barbell-front-squat', 'squat', ['quads'], ['glutes', 'abs', 'shoulders'], ['barbell', 'plates', 'rack'], 'advanced',
    ['elbows_high', 'upright_torso', 'controlled_descent'], ['elbows_drop', 'heels_lift'], ['set_safety_bars', 'release_bar_forward'],
    ['barbell-back-squat', 'goblet-squat', 'hack-squat-machine']),
  s('barbell-box-squat', 'squat', ['quads', 'glutes'], ['hamstrings', 'lower_back'], ['barbell', 'plates', 'rack'], 'intermediate',
    ['sit_back_to_box', 'pause_no_relax', 'drive_up'], ['bounce_off_box', 'round_lower_back'], ['set_safety_bars'],
    ['barbell-back-squat', 'chair-squat', 'leg-press']),
  s('goblet-squat', 'squat', ['quads', 'glutes'], ['abs', 'shoulders'], ['dumbbells'], 'beginner',
    ['hold_close_to_chest', 'elbows_inside_knees', 'chest_tall'], ['rounding_back', 'partial_depth'], ['start_light'],
    ['bodyweight-squat', 'dumbbell-squat', 'kettlebell-front-squat']),
  s('dumbbell-squat', 'squat', ['quads', 'glutes'], ['hamstrings', 'forearms'], ['dumbbells'], 'beginner',
    ['weights_at_sides', 'knees_track_toes', 'full_range'], ['leaning_forward', 'partial_depth'], ['start_light'],
    ['goblet-squat', 'bodyweight-squat', 'leg-press']),
  s('kettlebell-front-squat', 'squat', ['quads', 'glutes'], ['abs', 'shoulders'], ['kettlebell'], 'intermediate',
    ['rack_position', 'wrist_neutral', 'controlled_descent'], ['wrist_bent_back', 'torso_collapse'], ['start_light'],
    ['goblet-squat', 'barbell-front-squat', 'dumbbell-squat']),
  s('bodyweight-squat', 'squat', ['quads', 'glutes'], ['hamstrings', 'abs'], ['none'], 'beginner',
    ['feet_shoulder_width', 'hips_back_first', 'knees_track_toes'], ['knees_cave_in', 'heels_lift'], ['stop_if_joint_pain'],
    ['chair-squat', 'goblet-squat', 'wall-sit']),
  s('chair-squat', 'squat', ['quads', 'glutes'], ['abs'], ['none'], 'beginner',
    ['touch_seat_lightly', 'stand_without_hands', 'controlled_tempo'], ['dropping_onto_seat', 'knees_cave_in'], ['use_stable_chair'],
    ['bodyweight-squat', 'wall-sit', 'leg-press']),
  s('jump-squat', 'squat', ['quads', 'glutes'], ['calves', 'abs'], ['none'], 'intermediate',
    ['soft_landing', 'absorb_with_hips', 'reset_each_rep'], ['landing_stiff_knees', 'rushing_reps'], ['avoid_if_joint_pain', 'land_on_soft_surface'],
    ['bodyweight-squat', 'burpee', 'walking-lunge']),
  s('wall-sit', 'squat', ['quads'], ['glutes', 'abs'], ['none'], 'beginner',
    ['back_flat_on_wall', 'thighs_parallel', 'breathe_steadily'], ['sliding_down', 'holding_breath'], ['stop_if_joint_pain'],
    ['chair-squat', 'bodyweight-squat', 'leg-press']),
  s('band-squat', 'squat', ['quads', 'glutes'], ['abs'], ['bands'], 'beginner',
    ['band_under_midfoot', 'tension_all_range', 'chest_tall'], ['band_slipping', 'partial_depth'], ['check_band_wear'],
    ['bodyweight-squat', 'goblet-squat', 'dumbbell-squat']),
  s('leg-press', 'squat', ['quads', 'glutes'], ['hamstrings'], ['machines'], 'beginner',
    ['feet_mid_platform', 'knees_track_toes', 'no_lockout_slam'], ['lower_back_lifting', 'bouncing_bottom'], ['engage_safety_latch'],
    ['barbell-back-squat', 'hack-squat-machine', 'goblet-squat']),
  s('hack-squat-machine', 'squat', ['quads'], ['glutes', 'hamstrings'], ['machines'], 'intermediate',
    ['back_flat_on_pad', 'controlled_descent', 'drive_through_heels'], ['knees_cave_in', 'partial_depth'], ['engage_safety_latch'],
    ['leg-press', 'barbell-back-squat', 'barbell-front-squat']),

  /* ------------------------------------------------------------- bisagra */
  s('conventional-deadlift', 'hinge', ['hamstrings', 'glutes'], ['lower_back', 'back', 'traps', 'forearms'], ['barbell', 'plates'], 'intermediate',
    ['bar_over_midfoot', 'flat_back', 'push_floor_away'], ['rounding_lower_back', 'hips_rise_first'], ['reset_each_rep', 'stop_if_back_pain'],
    ['trap-bar-deadlift', 'romanian-deadlift', 'kettlebell-swing']),
  s('sumo-deadlift', 'hinge', ['glutes', 'quads'], ['hamstrings', 'lower_back', 'traps'], ['barbell', 'plates'], 'intermediate',
    ['wide_stance', 'knees_out', 'chest_up'], ['hips_rise_first', 'bar_drifting_forward'], ['stop_if_back_pain'],
    ['conventional-deadlift', 'trap-bar-deadlift', 'leg-press']),
  s('trap-bar-deadlift', 'hinge', ['glutes', 'quads'], ['hamstrings', 'traps', 'forearms'], ['barbell', 'plates'], 'beginner',
    ['stand_centered', 'flat_back', 'drive_through_floor'], ['rounding_lower_back', 'jerking_start'], ['reset_each_rep'],
    ['conventional-deadlift', 'romanian-deadlift', 'goblet-squat']),
  s('romanian-deadlift', 'hinge', ['hamstrings', 'glutes'], ['lower_back', 'back'], ['barbell', 'plates'], 'intermediate',
    ['soft_knees', 'hips_travel_back', 'bar_close_to_legs'], ['squatting_instead_of_hinging', 'rounding_back'], ['stop_before_back_rounds'],
    ['dumbbell-romanian-deadlift', 'good-morning', 'cable-pull-through']),
  s('dumbbell-romanian-deadlift', 'hinge', ['hamstrings', 'glutes'], ['lower_back'], ['dumbbells'], 'beginner',
    ['soft_knees', 'hips_back', 'feel_hamstring_stretch'], ['bending_knees_too_much', 'rounding_back'], ['stop_before_back_rounds'],
    ['romanian-deadlift', 'single-leg-rdl', 'glute-bridge']),
  s('single-leg-rdl', 'hinge', ['hamstrings', 'glutes'], ['lower_back', 'abs'], ['none'], 'intermediate',
    ['hips_square', 'slow_tempo', 'reach_toward_floor'], ['hip_opening_up', 'rushing_balance'], ['hold_support_if_needed'],
    ['dumbbell-romanian-deadlift', 'glute-bridge', 'single-leg-glute-bridge']),
  s('kettlebell-swing', 'hinge', ['glutes', 'hamstrings'], ['abs', 'lower_back', 'shoulders'], ['kettlebell'], 'intermediate',
    ['hinge_not_squat', 'snap_hips', 'arms_stay_relaxed'], ['lifting_with_arms', 'rounding_back'], ['clear_space_around', 'stop_if_back_pain'],
    ['conventional-deadlift', 'cable-pull-through', 'jump-squat']),
  s('barbell-hip-thrust', 'hinge', ['glutes'], ['hamstrings', 'abs'], ['barbell', 'plates', 'bench'], 'intermediate',
    ['chin_tucked', 'ribs_down', 'full_hip_extension'], ['overarching_lower_back', 'pushing_through_toes'], ['pad_the_bar'],
    ['glute-bridge', 'cable-pull-through', 'single-leg-glute-bridge']),
  s('glute-bridge', 'hinge', ['glutes'], ['hamstrings', 'abs'], ['none'], 'beginner',
    ['feet_flat_close', 'squeeze_at_top', 'ribs_down'], ['overarching_lower_back', 'pushing_through_toes'], ['stop_if_back_pain'],
    ['single-leg-glute-bridge', 'barbell-hip-thrust', 'dumbbell-romanian-deadlift']),
  s('single-leg-glute-bridge', 'hinge', ['glutes'], ['hamstrings', 'abs'], ['none'], 'intermediate',
    ['hips_level', 'squeeze_at_top', 'slow_lowering'], ['hip_dropping', 'arching_back'], ['stop_if_back_pain'],
    ['glute-bridge', 'barbell-hip-thrust', 'single-leg-rdl']),
  s('good-morning', 'hinge', ['hamstrings'], ['glutes', 'lower_back'], ['barbell', 'plates'], 'advanced',
    ['light_load', 'hips_back', 'flat_back'], ['rounding_back', 'going_too_heavy'], ['use_light_load_first', 'stop_if_back_pain'],
    ['romanian-deadlift', 'back-extension', 'band-good-morning']),
  s('band-good-morning', 'hinge', ['hamstrings', 'glutes'], ['lower_back'], ['bands'], 'beginner',
    ['band_under_feet', 'hips_back', 'flat_back'], ['rounding_back', 'band_slipping'], ['check_band_wear'],
    ['good-morning', 'glute-bridge', 'dumbbell-romanian-deadlift']),
  s('cable-pull-through', 'hinge', ['glutes', 'hamstrings'], ['lower_back'], ['cables'], 'beginner',
    ['face_away_from_stack', 'hinge_at_hips', 'squeeze_at_lockout'], ['squatting_the_movement', 'overextending_at_top'], ['keep_stable_stance'],
    ['kettlebell-swing', 'barbell-hip-thrust', 'romanian-deadlift']),
  s('back-extension', 'hinge', ['lower_back', 'glutes'], ['hamstrings'], ['machines'], 'beginner',
    ['pads_below_hip_crease', 'neutral_spine', 'stop_at_straight'], ['hyperextending_at_top', 'jerking_up'], ['stop_if_back_pain'],
    ['good-morning', 'glute-bridge', 'romanian-deadlift']),

  /* ------------------------------------------------------ empuje horizontal */
  s('barbell-bench-press', 'horizontal_push', ['chest'], ['triceps', 'shoulders'], ['barbell', 'plates', 'bench', 'rack'], 'intermediate',
    ['shoulder_blades_retracted', 'feet_planted', 'bar_to_lower_chest'], ['bouncing_off_chest', 'flaring_elbows'], ['use_spotter_or_safeties', 'no_thumbless_grip'],
    ['dumbbell-bench-press', 'machine-chest-press', 'push-up']),
  s('incline-barbell-bench-press', 'horizontal_push', ['chest', 'shoulders'], ['triceps'], ['barbell', 'plates', 'bench', 'rack'], 'intermediate',
    ['bench_30_degrees', 'blades_retracted', 'bar_to_upper_chest'], ['bench_too_steep', 'bouncing_off_chest'], ['use_spotter_or_safeties'],
    ['incline-dumbbell-press', 'barbell-bench-press', 'machine-chest-press']),
  s('dumbbell-bench-press', 'horizontal_push', ['chest'], ['triceps', 'shoulders'], ['dumbbells', 'bench'], 'beginner',
    ['blades_retracted', 'wrists_stacked', 'control_the_descent'], ['flaring_elbows', 'clanging_dumbbells'], ['set_down_safely'],
    ['barbell-bench-press', 'dumbbell-floor-press', 'push-up']),
  s('incline-dumbbell-press', 'horizontal_push', ['chest', 'shoulders'], ['triceps'], ['dumbbells', 'bench'], 'intermediate',
    ['bench_30_degrees', 'elbows_45_degrees', 'full_range'], ['bench_too_steep', 'short_range'], ['set_down_safely'],
    ['incline-barbell-bench-press', 'dumbbell-bench-press', 'pike-push-up']),
  s('dumbbell-floor-press', 'horizontal_push', ['chest', 'triceps'], ['shoulders'], ['dumbbells'], 'beginner',
    ['elbows_touch_floor', 'pause_briefly', 'press_straight_up'], ['bouncing_elbows', 'flaring_elbows'], ['set_down_safely'],
    ['dumbbell-bench-press', 'push-up', 'machine-chest-press']),
  s('push-up', 'horizontal_push', ['chest'], ['triceps', 'shoulders', 'abs'], ['none'], 'beginner',
    ['body_in_straight_line', 'elbows_45_degrees', 'full_range'], ['sagging_hips', 'flaring_elbows'], ['drop_to_knees_if_form_breaks'],
    ['knee-push-up', 'incline-push-up', 'dumbbell-bench-press']),
  s('knee-push-up', 'horizontal_push', ['chest'], ['triceps', 'abs'], ['none'], 'beginner',
    ['knees_hips_shoulders_aligned', 'chest_to_floor', 'controlled_tempo'], ['sagging_hips', 'half_range'], ['pad_the_knees'],
    ['incline-push-up', 'push-up', 'band-chest-press']),
  s('incline-push-up', 'horizontal_push', ['chest'], ['triceps', 'shoulders'], ['none'], 'beginner',
    ['hands_on_stable_surface', 'straight_body', 'chest_to_edge'], ['sagging_hips', 'unstable_surface'], ['use_stable_surface'],
    ['knee-push-up', 'push-up', 'machine-chest-press']),
  s('decline-push-up', 'horizontal_push', ['chest', 'shoulders'], ['triceps', 'abs'], ['none'], 'intermediate',
    ['feet_elevated', 'ribs_down', 'controlled_descent'], ['sagging_hips', 'neck_craning'], ['use_stable_surface'],
    ['push-up', 'incline-dumbbell-press', 'diamond-push-up']),
  s('diamond-push-up', 'horizontal_push', ['triceps', 'chest'], ['shoulders'], ['none'], 'intermediate',
    ['hands_form_triangle', 'elbows_close', 'straight_body'], ['flaring_elbows', 'sagging_hips'], ['stop_if_wrist_pain'],
    ['push-up', 'bench-dip', 'triceps-pushdown-cable']),
  s('machine-chest-press', 'horizontal_push', ['chest'], ['triceps', 'shoulders'], ['machines'], 'beginner',
    ['handles_at_chest_height', 'blades_back', 'no_lockout_slam'], ['seat_too_high', 'partial_range'], ['adjust_seat_first'],
    ['barbell-bench-press', 'dumbbell-bench-press', 'cable-chest-press']),
  s('cable-chest-press', 'horizontal_push', ['chest'], ['triceps', 'shoulders', 'abs'], ['cables'], 'beginner',
    ['staggered_stance', 'press_and_squeeze', 'control_the_return'], ['leaning_too_far', 'shrugging_shoulders'], ['check_pin_and_clips'],
    ['machine-chest-press', 'dumbbell-bench-press', 'band-chest-press']),
  s('band-chest-press', 'horizontal_push', ['chest'], ['triceps', 'shoulders'], ['bands'], 'beginner',
    ['band_behind_back', 'press_forward', 'slow_return'], ['band_slipping', 'short_range'], ['check_band_wear'],
    ['push-up', 'cable-chest-press', 'dumbbell-bench-press']),
  s('bench-dip', 'horizontal_push', ['triceps'], ['chest', 'shoulders'], ['bench'], 'beginner',
    ['hands_at_bench_edge', 'elbows_back', 'stop_at_parallel'], ['going_too_deep', 'shoulders_shrugging'], ['stop_if_shoulder_pain'],
    ['diamond-push-up', 'parallel-bar-dip', 'triceps-pushdown-cable']),
  s('parallel-bar-dip', 'horizontal_push', ['chest', 'triceps'], ['shoulders'], ['machines'], 'advanced',
    ['slight_forward_lean', 'elbows_back', 'stop_at_shoulder_height'], ['going_too_deep', 'swinging_legs'], ['stop_if_shoulder_pain', 'use_assistance_if_needed'],
    ['bench-dip', 'push-up', 'machine-chest-press']),

  /* -------------------------------------------------------- empuje vertical */
  s('barbell-overhead-press', 'vertical_push', ['shoulders'], ['triceps', 'abs', 'traps'], ['barbell', 'plates'], 'intermediate',
    ['squeeze_glutes', 'head_through_at_top', 'bar_over_midfoot'], ['overarching_lower_back', 'pressing_around_head'], ['stop_if_shoulder_pain'],
    ['dumbbell-shoulder-press', 'machine-shoulder-press', 'pike-push-up']),
  s('push-press', 'vertical_push', ['shoulders'], ['triceps', 'quads', 'abs'], ['barbell', 'plates'], 'advanced',
    ['short_dip', 'drive_with_legs', 'lock_out_overhead'], ['dipping_too_deep', 'overarching_lower_back'], ['clear_space_overhead'],
    ['barbell-overhead-press', 'kettlebell-overhead-press', 'dumbbell-shoulder-press']),
  s('dumbbell-shoulder-press', 'vertical_push', ['shoulders'], ['triceps', 'abs'], ['dumbbells'], 'beginner',
    ['ribs_down', 'press_slightly_forward', 'full_lockout'], ['overarching_lower_back', 'half_range'], ['stop_if_shoulder_pain'],
    ['seated-dumbbell-shoulder-press', 'barbell-overhead-press', 'band-overhead-press']),
  s('seated-dumbbell-shoulder-press', 'vertical_push', ['shoulders'], ['triceps'], ['dumbbells', 'bench'], 'beginner',
    ['back_against_pad', 'wrists_stacked', 'controlled_descent'], ['bouncing_off_shoulders', 'arching_off_pad'], ['set_down_safely'],
    ['dumbbell-shoulder-press', 'machine-shoulder-press', 'arnold-press']),
  s('arnold-press', 'vertical_push', ['shoulders'], ['triceps'], ['dumbbells'], 'intermediate',
    ['start_palms_in', 'rotate_as_you_press', 'controlled_tempo'], ['rushing_the_rotation', 'using_momentum'], ['stop_if_shoulder_pain'],
    ['dumbbell-shoulder-press', 'seated-dumbbell-shoulder-press', 'machine-shoulder-press']),
  s('kettlebell-overhead-press', 'vertical_push', ['shoulders'], ['triceps', 'abs'], ['kettlebell'], 'intermediate',
    ['rack_position', 'wrist_neutral', 'press_and_lock'], ['wrist_bent_back', 'leaning_sideways'], ['stop_if_shoulder_pain'],
    ['dumbbell-shoulder-press', 'barbell-overhead-press', 'push-press']),
  s('landmine-press', 'vertical_push', ['shoulders', 'chest'], ['triceps', 'abs'], ['barbell', 'plates'], 'intermediate',
    ['staggered_stance', 'press_up_and_forward', 'ribs_down'], ['leaning_back', 'shrugging_shoulders'], ['secure_the_bar_end'],
    ['barbell-overhead-press', 'dumbbell-shoulder-press', 'incline-dumbbell-press']),
  s('pike-push-up', 'vertical_push', ['shoulders'], ['triceps', 'abs'], ['none'], 'intermediate',
    ['hips_high', 'crown_toward_floor', 'elbows_forward'], ['bending_at_waist_only', 'neck_compressing'], ['stop_if_shoulder_pain'],
    ['push-up', 'dumbbell-shoulder-press', 'wall-handstand-push-up']),
  s('wall-handstand-push-up', 'vertical_push', ['shoulders'], ['triceps', 'abs'], ['none'], 'advanced',
    ['hands_close_to_wall', 'ribs_down', 'controlled_descent'], ['collapsing_neck_first', 'excessive_arching'], ['have_an_exit_plan', 'clear_space_around'],
    ['pike-push-up', 'barbell-overhead-press', 'dumbbell-shoulder-press']),
  s('machine-shoulder-press', 'vertical_push', ['shoulders'], ['triceps'], ['machines'], 'beginner',
    ['handles_at_shoulder_height', 'back_on_pad', 'no_lockout_slam'], ['seat_too_low', 'partial_range'], ['adjust_seat_first'],
    ['dumbbell-shoulder-press', 'barbell-overhead-press', 'band-overhead-press']),
  s('band-overhead-press', 'vertical_push', ['shoulders'], ['triceps', 'abs'], ['bands'], 'beginner',
    ['band_under_feet', 'ribs_down', 'slow_return'], ['band_slipping', 'leaning_back'], ['check_band_wear'],
    ['dumbbell-shoulder-press', 'pike-push-up', 'machine-shoulder-press']),

  /* ---------------------------------------------------------- tirón horizontal */
  s('barbell-bent-over-row', 'horizontal_pull', ['back', 'lats'], ['biceps', 'lower_back', 'traps'], ['barbell', 'plates'], 'intermediate',
    ['hinge_to_45_degrees', 'pull_to_navel', 'flat_back'], ['jerking_with_lower_back', 'standing_too_upright'], ['stop_if_back_pain'],
    ['pendlay-row', 'dumbbell-one-arm-row', 'seated-cable-row']),
  s('pendlay-row', 'horizontal_pull', ['back', 'lats'], ['biceps', 'traps'], ['barbell', 'plates'], 'advanced',
    ['torso_parallel', 'reset_on_floor', 'explosive_pull'], ['rounding_back', 'torso_rising'], ['stop_if_back_pain'],
    ['barbell-bent-over-row', 't-bar-row', 'chest-supported-dumbbell-row']),
  s('t-bar-row', 'horizontal_pull', ['back', 'lats'], ['biceps', 'traps'], ['barbell', 'plates'], 'intermediate',
    ['chest_up', 'pull_to_sternum', 'squeeze_blades'], ['rounding_back', 'using_momentum'], ['secure_the_bar_end'],
    ['barbell-bent-over-row', 'machine-seated-row', 'chest-supported-dumbbell-row']),
  s('dumbbell-one-arm-row', 'horizontal_pull', ['lats', 'back'], ['biceps', 'traps'], ['dumbbells', 'bench'], 'beginner',
    ['flat_back', 'pull_to_hip', 'no_torso_rotation'], ['twisting_the_torso', 'shrugging'], ['support_on_stable_bench'],
    ['chest-supported-dumbbell-row', 'seated-cable-row', 'inverted-row']),
  s('chest-supported-dumbbell-row', 'horizontal_pull', ['back', 'lats'], ['biceps', 'traps'], ['dumbbells', 'bench'], 'beginner',
    ['chest_stays_on_pad', 'elbows_to_ribs', 'squeeze_blades'], ['lifting_chest_off_pad', 'using_momentum'], ['set_down_safely'],
    ['dumbbell-one-arm-row', 'machine-seated-row', 'seated-cable-row']),
  s('kettlebell-row', 'horizontal_pull', ['lats', 'back'], ['biceps', 'forearms'], ['kettlebell'], 'beginner',
    ['hinge_and_brace', 'pull_to_hip', 'flat_back'], ['rounding_back', 'twisting_torso'], ['stop_if_back_pain'],
    ['dumbbell-one-arm-row', 'inverted-row', 'seated-cable-row']),
  s('inverted-row', 'horizontal_pull', ['back', 'lats'], ['biceps', 'abs'], ['none'], 'beginner',
    ['body_straight', 'chest_to_bar', 'squeeze_blades'], ['sagging_hips', 'half_range'], ['test_the_support_first'],
    ['dumbbell-one-arm-row', 'band-seated-row', 'seated-cable-row']),
  s('band-seated-row', 'horizontal_pull', ['back', 'lats'], ['biceps'], ['bands'], 'beginner',
    ['tall_posture', 'pull_to_ribs', 'slow_return'], ['leaning_back', 'shrugging'], ['check_band_wear'],
    ['inverted-row', 'seated-cable-row', 'dumbbell-one-arm-row']),
  s('seated-cable-row', 'horizontal_pull', ['back', 'lats'], ['biceps', 'traps'], ['cables'], 'beginner',
    ['tall_chest', 'pull_to_navel', 'control_the_return'], ['rocking_the_torso', 'shrugging'], ['check_pin_and_clips'],
    ['machine-seated-row', 'dumbbell-one-arm-row', 'inverted-row']),
  s('machine-seated-row', 'horizontal_pull', ['back', 'lats'], ['biceps'], ['machines'], 'beginner',
    ['chest_on_pad', 'elbows_to_ribs', 'full_range'], ['lifting_off_the_pad', 'partial_range'], ['adjust_seat_first'],
    ['seated-cable-row', 'chest-supported-dumbbell-row', 'barbell-bent-over-row']),
  s('cable-face-pull', 'horizontal_pull', ['shoulders', 'traps'], ['back', 'biceps'], ['cables'], 'beginner',
    ['rope_at_eye_level', 'pull_to_forehead', 'elbows_high'], ['using_too_much_weight', 'shrugging'], ['keep_load_light'],
    ['band-face-pull', 'rear-delt-fly-dumbbell', 'prone-y-t-raise']),
  s('band-face-pull', 'horizontal_pull', ['shoulders', 'traps'], ['back'], ['bands'], 'beginner',
    ['anchor_at_chest_height', 'pull_to_forehead', 'squeeze_rear_delts'], ['shrugging', 'band_slipping'], ['check_band_wear'],
    ['cable-face-pull', 'rear-delt-fly-dumbbell', 'prone-y-t-raise']),

  /* ------------------------------------------------------------ tirón vertical */
  s('pull-up', 'vertical_pull', ['lats', 'back'], ['biceps', 'forearms', 'abs'], ['rack'], 'advanced',
    ['start_from_dead_hang', 'pull_elbows_down', 'chin_over_bar'], ['kipping_unintentionally', 'half_range'], ['check_bar_is_secure'],
    ['chin-up', 'lat-pulldown-cable', 'band-assisted-pull-up']),
  s('chin-up', 'vertical_pull', ['lats', 'biceps'], ['back', 'forearms'], ['rack'], 'intermediate',
    ['supinated_grip', 'chest_to_bar', 'controlled_descent'], ['swinging', 'half_range'], ['check_bar_is_secure'],
    ['pull-up', 'lat-pulldown-cable', 'negative-pull-up']),
  s('neutral-grip-pull-up', 'vertical_pull', ['lats', 'back'], ['biceps', 'forearms'], ['rack'], 'intermediate',
    ['palms_facing', 'elbows_down_and_back', 'full_hang'], ['swinging', 'shrugging_at_bottom'], ['check_bar_is_secure', 'stop_if_shoulder_pain'],
    ['pull-up', 'chin-up', 'lat-pulldown-machine']),
  s('negative-pull-up', 'vertical_pull', ['lats', 'back'], ['biceps'], ['rack'], 'beginner',
    ['start_at_top', 'lower_for_five_seconds', 'stay_tight'], ['dropping_too_fast', 'skipping_the_setup'], ['check_bar_is_secure'],
    ['band-assisted-pull-up', 'assisted-pull-up-machine', 'lat-pulldown-cable']),
  s('band-assisted-pull-up', 'vertical_pull', ['lats', 'back'], ['biceps'], ['rack', 'bands'], 'beginner',
    ['band_under_knee', 'full_hang_start', 'controlled_descent'], ['bouncing_out_of_the_band', 'half_range'], ['check_band_wear', 'check_bar_is_secure'],
    ['negative-pull-up', 'assisted-pull-up-machine', 'band-lat-pulldown']),
  s('assisted-pull-up-machine', 'vertical_pull', ['lats', 'back'], ['biceps'], ['machines'], 'beginner',
    ['set_assist_weight', 'full_range', 'controlled_descent'], ['too_much_assistance', 'partial_range'], ['step_off_carefully'],
    ['lat-pulldown-machine', 'negative-pull-up', 'chin-up']),
  s('lat-pulldown-cable', 'vertical_pull', ['lats'], ['back', 'biceps'], ['cables'], 'beginner',
    ['thighs_under_pad', 'pull_to_upper_chest', 'slow_return'], ['leaning_way_back', 'pulling_behind_neck'], ['never_pull_behind_neck'],
    ['lat-pulldown-machine', 'pull-up', 'band-lat-pulldown']),
  s('lat-pulldown-machine', 'vertical_pull', ['lats'], ['back', 'biceps'], ['machines'], 'beginner',
    ['secure_the_thigh_pad', 'elbows_drive_down', 'full_stretch_at_top'], ['using_momentum', 'partial_range'], ['adjust_seat_first'],
    ['lat-pulldown-cable', 'assisted-pull-up-machine', 'chin-up']),
  s('band-lat-pulldown', 'vertical_pull', ['lats'], ['back', 'biceps'], ['bands'], 'beginner',
    ['anchor_overhead', 'elbows_to_ribs', 'slow_return'], ['band_slipping', 'short_range'], ['check_anchor_point', 'check_band_wear'],
    ['lat-pulldown-cable', 'inverted-row', 'band-seated-row']),
  s('straight-arm-pulldown', 'vertical_pull', ['lats'], ['back', 'triceps'], ['cables'], 'intermediate',
    ['slight_forward_lean', 'arms_nearly_straight', 'squeeze_lats'], ['bending_elbows', 'using_bodyweight'], ['keep_load_light'],
    ['lat-pulldown-cable', 'band-lat-pulldown', 'seated-cable-row']),

  /* ------------------------------------------------------------------ zancada */
  s('walking-lunge', 'lunge', ['quads', 'glutes'], ['hamstrings', 'abs'], ['none'], 'beginner',
    ['long_step', 'back_knee_toward_floor', 'torso_tall'], ['front_knee_caving', 'steps_too_short'], ['stop_if_knee_pain'],
    ['reverse-lunge', 'split-squat', 'dumbbell-walking-lunge']),
  s('reverse-lunge', 'lunge', ['quads', 'glutes'], ['hamstrings'], ['none'], 'beginner',
    ['step_straight_back', 'weight_on_front_foot', 'controlled_return'], ['front_knee_caving', 'leaning_forward'], ['stop_if_knee_pain'],
    ['walking-lunge', 'split-squat', 'step-up']),
  s('split-squat', 'lunge', ['quads', 'glutes'], ['hamstrings', 'abs'], ['none'], 'beginner',
    ['feet_in_two_tracks', 'vertical_shin', 'even_tempo'], ['feet_on_a_tightrope', 'bouncing_at_bottom'], ['hold_support_if_needed'],
    ['reverse-lunge', 'bulgarian-split-squat', 'walking-lunge']),
  s('bulgarian-split-squat', 'lunge', ['quads', 'glutes'], ['hamstrings', 'abs'], ['none'], 'intermediate',
    ['rear_foot_elevated', 'hips_square', 'slow_descent'], ['rear_foot_too_close', 'losing_balance'], ['use_stable_surface'],
    ['split-squat', 'dumbbell-bulgarian-split-squat', 'reverse-lunge']),
  s('lateral-lunge', 'lunge', ['quads', 'glutes'], ['hamstrings', 'obliques'], ['none'], 'beginner',
    ['step_wide_sideways', 'sit_into_hip', 'other_leg_straight'], ['knee_past_toes_sideways', 'rounding_back'], ['stop_if_groin_discomfort'],
    ['walking-lunge', 'curtsy-lunge', 'split-squat']),
  s('curtsy-lunge', 'lunge', ['glutes', 'quads'], ['hamstrings', 'obliques'], ['none'], 'intermediate',
    ['step_behind_and_across', 'hips_facing_forward', 'controlled_tempo'], ['twisting_the_knee', 'losing_balance'], ['stop_if_knee_pain'],
    ['lateral-lunge', 'reverse-lunge', 'split-squat']),
  s('step-up', 'lunge', ['quads', 'glutes'], ['hamstrings', 'calves'], ['none'], 'beginner',
    ['full_foot_on_box', 'drive_through_heel', 'lower_under_control'], ['pushing_off_back_foot', 'box_too_high'], ['use_stable_surface'],
    ['dumbbell-step-up', 'reverse-lunge', 'split-squat']),
  s('dumbbell-walking-lunge', 'lunge', ['quads', 'glutes'], ['hamstrings', 'forearms'], ['dumbbells'], 'intermediate',
    ['weights_at_sides', 'long_step', 'torso_tall'], ['front_knee_caving', 'leaning_forward'], ['clear_space_ahead'],
    ['walking-lunge', 'dumbbell-step-up', 'barbell-lunge']),
  s('dumbbell-bulgarian-split-squat', 'lunge', ['quads', 'glutes'], ['hamstrings'], ['dumbbells'], 'intermediate',
    ['rear_foot_elevated', 'weights_at_sides', 'slow_descent'], ['losing_balance', 'rear_foot_too_close'], ['use_stable_surface'],
    ['bulgarian-split-squat', 'dumbbell-walking-lunge', 'split-squat']),
  s('dumbbell-step-up', 'lunge', ['quads', 'glutes'], ['calves', 'forearms'], ['dumbbells'], 'beginner',
    ['full_foot_on_box', 'drive_through_heel', 'controlled_descent'], ['pushing_off_back_foot', 'box_too_high'], ['use_stable_surface'],
    ['step-up', 'dumbbell-walking-lunge', 'leg-press']),
  s('barbell-lunge', 'lunge', ['quads', 'glutes'], ['hamstrings', 'abs'], ['barbell', 'plates'], 'advanced',
    ['bar_settled_on_traps', 'long_step', 'brace_core'], ['losing_balance', 'short_steps'], ['clear_space_ahead', 'set_safety_bars'],
    ['dumbbell-walking-lunge', 'walking-lunge', 'bulgarian-split-squat']),

  /* ------------------------------------------------------------------ acarreo */
  s('farmers-carry-dumbbells', 'carry', ['forearms', 'traps'], ['abs', 'obliques', 'glutes'], ['dumbbells'], 'beginner',
    ['stand_tall', 'ribs_down', 'short_quick_steps'], ['leaning_to_one_side', 'shrugging'], ['clear_the_path', 'set_down_safely'],
    ['kettlebell-farmers-carry', 'suitcase-carry', 'backpack-carry']),
  s('kettlebell-farmers-carry', 'carry', ['forearms', 'traps'], ['abs', 'glutes'], ['kettlebell'], 'beginner',
    ['stand_tall', 'brace_core', 'steady_breathing'], ['leaning_to_one_side', 'holding_breath'], ['clear_the_path'],
    ['farmers-carry-dumbbells', 'suitcase-carry', 'front-rack-carry-kettlebell']),
  s('suitcase-carry', 'carry', ['obliques', 'forearms'], ['abs', 'traps'], ['dumbbells'], 'beginner',
    ['load_on_one_side', 'resist_the_lean', 'even_steps'], ['leaning_toward_the_weight', 'rushing'], ['alternate_sides', 'set_down_safely'],
    ['farmers-carry-dumbbells', 'kettlebell-farmers-carry', 'backpack-carry']),
  s('overhead-carry-dumbbell', 'carry', ['shoulders', 'abs'], ['traps', 'obliques'], ['dumbbells'], 'intermediate',
    ['elbow_locked', 'ribs_down', 'eyes_forward'], ['overarching_lower_back', 'letting_the_arm_drift'], ['clear_space_overhead', 'stop_if_shoulder_pain'],
    ['front-rack-carry-kettlebell', 'farmers-carry-dumbbells', 'suitcase-carry']),
  s('front-rack-carry-kettlebell', 'carry', ['abs', 'shoulders'], ['obliques', 'traps'], ['kettlebell'], 'intermediate',
    ['rack_position', 'ribs_down', 'steady_breathing'], ['leaning_back', 'wrist_bent_back'], ['set_down_safely'],
    ['overhead-carry-dumbbell', 'kettlebell-farmers-carry', 'farmers-carry-dumbbells']),
  s('plate-carry', 'carry', ['shoulders', 'abs'], ['forearms', 'traps'], ['plates'], 'beginner',
    ['plate_at_chest_height', 'arms_extended', 'stand_tall'], ['letting_plate_drop', 'leaning_back'], ['clear_the_path'],
    ['farmers-carry-dumbbells', 'backpack-carry', 'suitcase-carry']),
  s('backpack-carry', 'carry', ['abs', 'traps'], ['obliques', 'glutes', 'forearms'], ['none'], 'beginner',
    ['load_close_to_body', 'stand_tall', 'even_steps'], ['leaning_forward', 'overloading_the_bag'], ['clear_the_path'],
    ['farmers-carry-dumbbells', 'suitcase-carry', 'plate-carry']),

  /* --------------------------------------------------------------------- core */
  s('plank', 'core', ['abs'], ['obliques', 'shoulders', 'glutes'], ['none'], 'beginner',
    ['elbows_under_shoulders', 'ribs_down', 'squeeze_glutes'], ['hips_sagging', 'hips_too_high'], ['stop_if_back_pain'],
    ['dead-bug', 'side-plank', 'hollow-hold']),
  s('side-plank', 'core', ['obliques'], ['abs', 'shoulders', 'glutes'], ['none'], 'beginner',
    ['elbow_under_shoulder', 'hips_stacked', 'lift_the_hip'], ['hips_dropping', 'rotating_forward'], ['stop_if_shoulder_pain'],
    ['plank', 'copenhagen-plank', 'pallof-press-cable']),
  s('dead-bug', 'core', ['abs'], ['obliques', 'lower_back'], ['none'], 'beginner',
    ['lower_back_flat', 'opposite_arm_and_leg', 'exhale_on_extension'], ['back_arching_off_floor', 'moving_too_fast'], ['reduce_range_if_back_arches'],
    ['plank', 'bird-dog', 'hollow-hold']),
  s('bird-dog', 'core', ['abs', 'lower_back'], ['glutes', 'shoulders'], ['none'], 'beginner',
    ['flat_back', 'extend_opposite_limbs', 'no_hip_rotation'], ['arching_the_back', 'rushing'], ['stop_if_back_pain'],
    ['dead-bug', 'plank', 'side-plank']),
  s('hollow-hold', 'core', ['abs'], ['obliques'], ['none'], 'intermediate',
    ['lower_back_pressed_down', 'shoulders_off_floor', 'steady_breathing'], ['back_arching_off_floor', 'holding_breath'], ['bend_knees_to_regress'],
    ['dead-bug', 'plank', 'lying-leg-raise']),
  s('lying-leg-raise', 'core', ['abs'], ['obliques'], ['none'], 'beginner',
    ['hands_under_hips', 'legs_straight', 'lower_slowly'], ['back_arching_off_floor', 'using_momentum'], ['bend_knees_to_regress'],
    ['reverse-crunch', 'hanging-knee-raise', 'dead-bug']),
  s('reverse-crunch', 'core', ['abs'], ['obliques'], ['none'], 'beginner',
    ['curl_hips_off_floor', 'knees_toward_chest', 'slow_lowering'], ['swinging_the_legs', 'pulling_with_neck'], ['stop_if_back_pain'],
    ['lying-leg-raise', 'hanging-knee-raise', 'hollow-hold']),
  s('hanging-knee-raise', 'core', ['abs'], ['obliques', 'forearms'], ['rack'], 'intermediate',
    ['stop_the_swing', 'curl_the_pelvis', 'lower_under_control'], ['swinging', 'only_bending_hips'], ['check_bar_is_secure'],
    ['lying-leg-raise', 'reverse-crunch', 'machine-ab-crunch']),
  s('mountain-climber', 'core', ['abs'], ['shoulders', 'quads', 'obliques'], ['none'], 'beginner',
    ['plank_position', 'hips_low', 'quick_but_controlled'], ['hips_bouncing_up', 'short_range'], ['stop_if_wrist_pain'],
    ['plank', 'high-knees', 'burpee']),
  s('plank-to-push-up', 'core', ['abs'], ['shoulders', 'triceps', 'chest'], ['none'], 'intermediate',
    ['minimize_hip_rotation', 'one_arm_at_a_time', 'ribs_down'], ['hips_swinging', 'sagging_hips'], ['stop_if_wrist_pain'],
    ['plank', 'push-up', 'mountain-climber']),
  s('russian-twist', 'core', ['obliques'], ['abs'], ['none'], 'beginner',
    ['tall_chest', 'rotate_from_ribs', 'controlled_tempo'], ['rounding_the_back', 'moving_only_the_arms'], ['stop_if_back_pain'],
    ['side-plank', 'pallof-press-band', 'bird-dog']),
  s('copenhagen-plank', 'core', ['obliques'], ['abs', 'glutes'], ['none'], 'advanced',
    ['top_leg_on_support', 'hips_high', 'short_holds_first'], ['hips_dropping', 'holding_too_long'], ['start_with_bent_knee', 'stop_if_groin_discomfort'],
    ['side-plank', 'plank', 'hip-abduction-band']),
  s('pallof-press-cable', 'core', ['obliques', 'abs'], ['shoulders'], ['cables'], 'beginner',
    ['stand_side_on', 'press_straight_out', 'resist_rotation'], ['letting_the_torso_turn', 'holding_breath'], ['keep_load_light'],
    ['pallof-press-band', 'side-plank', 'russian-twist']),
  s('pallof-press-band', 'core', ['obliques', 'abs'], ['shoulders'], ['bands'], 'beginner',
    ['anchor_at_chest_height', 'press_and_hold', 'resist_rotation'], ['letting_the_torso_turn', 'band_slipping'], ['check_anchor_point'],
    ['pallof-press-cable', 'side-plank', 'russian-twist']),
  s('cable-crunch', 'core', ['abs'], ['obliques'], ['cables'], 'beginner',
    ['hips_stay_fixed', 'curl_the_spine', 'exhale_at_bottom'], ['pulling_with_arms', 'hinging_at_hips'], ['check_pin_and_clips'],
    ['machine-ab-crunch', 'reverse-crunch', 'hanging-knee-raise']),
  s('machine-ab-crunch', 'core', ['abs'], ['obliques'], ['machines'], 'beginner',
    ['align_pivot_with_ribs', 'curl_not_hinge', 'slow_return'], ['using_momentum', 'partial_range'], ['adjust_seat_first'],
    ['cable-crunch', 'reverse-crunch', 'lying-leg-raise']),

  /* ---------------------------------------------------------------- aislamiento */
  s('dumbbell-biceps-curl', 'isolation', ['biceps'], ['forearms'], ['dumbbells'], 'beginner',
    ['elbows_at_sides', 'full_range', 'slow_lowering'], ['swinging_the_torso', 'elbows_drifting_forward'], ['start_light'],
    ['hammer-curl', 'barbell-biceps-curl', 'band-biceps-curl']),
  s('barbell-biceps-curl', 'isolation', ['biceps'], ['forearms'], ['barbell', 'plates'], 'beginner',
    ['elbows_pinned', 'no_torso_swing', 'controlled_tempo'], ['using_the_lower_back', 'half_range'], ['stop_if_elbow_pain'],
    ['dumbbell-biceps-curl', 'cable-biceps-curl', 'hammer-curl']),
  s('hammer-curl', 'isolation', ['biceps', 'forearms'], [], ['dumbbells'], 'beginner',
    ['neutral_grip', 'elbows_at_sides', 'slow_lowering'], ['swinging_the_torso', 'shrugging'], ['start_light'],
    ['dumbbell-biceps-curl', 'cable-biceps-curl', 'band-biceps-curl']),
  s('cable-biceps-curl', 'isolation', ['biceps'], ['forearms'], ['cables'], 'beginner',
    ['constant_tension', 'elbows_fixed', 'full_range'], ['leaning_back', 'using_momentum'], ['check_pin_and_clips'],
    ['dumbbell-biceps-curl', 'barbell-biceps-curl', 'band-biceps-curl']),
  s('band-biceps-curl', 'isolation', ['biceps'], ['forearms'], ['bands'], 'beginner',
    ['band_under_feet', 'elbows_at_sides', 'slow_return'], ['band_slipping', 'half_range'], ['check_band_wear'],
    ['dumbbell-biceps-curl', 'hammer-curl', 'cable-biceps-curl']),
  s('triceps-pushdown-cable', 'isolation', ['triceps'], [], ['cables'], 'beginner',
    ['elbows_pinned_to_ribs', 'extend_fully', 'slow_return'], ['elbows_flaring_out', 'leaning_over_the_bar'], ['check_pin_and_clips'],
    ['band-triceps-pushdown', 'overhead-triceps-extension-dumbbell', 'bench-dip']),
  s('band-triceps-pushdown', 'isolation', ['triceps'], [], ['bands'], 'beginner',
    ['anchor_overhead', 'elbows_pinned', 'full_extension'], ['band_slipping', 'elbows_flaring_out'], ['check_anchor_point'],
    ['triceps-pushdown-cable', 'overhead-triceps-extension-dumbbell', 'diamond-push-up']),
  s('overhead-triceps-extension-dumbbell', 'isolation', ['triceps'], ['shoulders'], ['dumbbells'], 'beginner',
    ['elbows_close_to_head', 'ribs_down', 'controlled_descent'], ['elbows_flaring_out', 'arching_the_back'], ['start_light', 'stop_if_elbow_pain'],
    ['triceps-pushdown-cable', 'skull-crusher', 'band-triceps-pushdown']),
  s('skull-crusher', 'isolation', ['triceps'], [], ['barbell', 'plates', 'bench'], 'intermediate',
    ['elbows_stay_still', 'lower_behind_forehead', 'no_lockout_slam'], ['elbows_drifting', 'bouncing_the_bar'], ['use_spotter_or_safeties', 'stop_if_elbow_pain'],
    ['overhead-triceps-extension-dumbbell', 'triceps-pushdown-cable', 'bench-dip']),
  s('lateral-raise-dumbbell', 'isolation', ['shoulders'], ['traps'], ['dumbbells'], 'beginner',
    ['slight_elbow_bend', 'lead_with_elbows', 'stop_at_shoulder_height'], ['shrugging', 'swinging_the_weights'], ['keep_load_light'],
    ['band-lateral-raise', 'machine-shoulder-press', 'cable-face-pull']),
  s('band-lateral-raise', 'isolation', ['shoulders'], ['traps'], ['bands'], 'beginner',
    ['band_under_feet', 'lead_with_elbows', 'slow_return'], ['shrugging', 'band_slipping'], ['check_band_wear'],
    ['lateral-raise-dumbbell', 'cable-face-pull', 'prone-y-t-raise']),
  s('rear-delt-fly-dumbbell', 'isolation', ['shoulders'], ['back', 'traps'], ['dumbbells'], 'beginner',
    ['hinge_forward', 'thumbs_slightly_down', 'squeeze_rear_delts'], ['using_too_much_weight', 'rowing_instead_of_flying'], ['keep_load_light'],
    ['cable-face-pull', 'band-face-pull', 'prone-y-t-raise']),
  s('prone-y-t-raise', 'isolation', ['shoulders', 'traps'], ['back'], ['none'], 'beginner',
    ['lie_face_down', 'thumbs_up', 'lift_from_the_blades'], ['shrugging', 'lifting_the_head'], ['keep_range_comfortable'],
    ['band-face-pull', 'rear-delt-fly-dumbbell', 'cable-face-pull']),
  s('dumbbell-chest-fly', 'isolation', ['chest'], ['shoulders'], ['dumbbells', 'bench'], 'intermediate',
    ['slight_elbow_bend', 'wide_arc', 'stop_at_chest_level'], ['going_too_deep', 'turning_it_into_a_press'], ['start_light', 'stop_if_shoulder_pain'],
    ['cable-chest-fly', 'dumbbell-bench-press', 'machine-chest-press']),
  s('cable-chest-fly', 'isolation', ['chest'], ['shoulders'], ['cables'], 'beginner',
    ['staggered_stance', 'constant_tension', 'squeeze_at_the_front'], ['bending_the_elbows_too_much', 'leaning_forward'], ['check_pin_and_clips'],
    ['dumbbell-chest-fly', 'cable-chest-press', 'machine-chest-press']),
  s('leg-extension-machine', 'isolation', ['quads'], [], ['machines'], 'beginner',
    ['align_knee_with_pivot', 'extend_smoothly', 'slow_return'], ['slamming_into_extension', 'partial_range'], ['adjust_seat_first', 'stop_if_knee_pain'],
    ['bodyweight-squat', 'leg-press', 'wall-sit']),
  s('leg-curl-machine', 'isolation', ['hamstrings'], ['calves'], ['machines'], 'beginner',
    ['align_knee_with_pivot', 'curl_fully', 'slow_return'], ['lifting_the_hips', 'partial_range'], ['adjust_seat_first'],
    ['nordic-hamstring-curl', 'dumbbell-romanian-deadlift', 'glute-bridge']),
  s('nordic-hamstring-curl', 'isolation', ['hamstrings'], ['glutes', 'abs'], ['none'], 'advanced',
    ['anchor_the_ankles', 'lower_as_slowly_as_possible', 'hips_extended'], ['bending_at_the_hips', 'dropping_too_fast'], ['use_hands_to_catch', 'expect_soreness_first_weeks'],
    ['leg-curl-machine', 'single-leg-rdl', 'glute-bridge']),
  s('standing-calf-raise', 'isolation', ['calves'], [], ['none'], 'beginner',
    ['full_stretch_at_bottom', 'pause_at_top', 'slow_tempo'], ['bouncing', 'short_range'], ['hold_support_if_needed'],
    ['dumbbell-calf-raise', 'calf-raise-machine', 'jump-squat']),
  s('dumbbell-calf-raise', 'isolation', ['calves'], ['forearms'], ['dumbbells'], 'beginner',
    ['weights_at_sides', 'full_range', 'pause_at_top'], ['bouncing', 'short_range'], ['hold_support_if_needed'],
    ['standing-calf-raise', 'calf-raise-machine', 'leg-press']),
  s('calf-raise-machine', 'isolation', ['calves'], [], ['machines'], 'beginner',
    ['shoulders_under_pads', 'full_stretch', 'controlled_tempo'], ['bouncing', 'locking_the_knees_hard'], ['adjust_seat_first'],
    ['standing-calf-raise', 'dumbbell-calf-raise', 'leg-press']),
  s('dumbbell-shrug', 'isolation', ['traps'], ['forearms'], ['dumbbells'], 'beginner',
    ['straight_up_and_down', 'pause_at_top', 'no_rolling'], ['rolling_the_shoulders', 'using_the_lower_back'], ['stop_if_neck_discomfort'],
    ['farmers-carry-dumbbells', 'cable-face-pull', 'barbell-bent-over-row']),
  s('wrist-curl-dumbbell', 'isolation', ['forearms'], [], ['dumbbells'], 'beginner',
    ['forearm_supported', 'small_controlled_range', 'light_load'], ['using_too_much_weight', 'jerking'], ['stop_if_wrist_pain'],
    ['farmers-carry-dumbbells', 'hammer-curl', 'dumbbell-shrug']),
  s('glute-kickback-band', 'isolation', ['glutes'], ['hamstrings', 'lower_back'], ['bands'], 'beginner',
    ['flat_back', 'drive_heel_back', 'squeeze_at_top'], ['arching_the_lower_back', 'swinging_the_leg'], ['check_band_wear'],
    ['glute-bridge', 'single-leg-glute-bridge', 'cable-pull-through']),
  s('hip-abduction-band', 'isolation', ['glutes'], ['obliques'], ['bands'], 'beginner',
    ['band_above_knees', 'open_without_rocking', 'slow_return'], ['rocking_the_torso', 'band_too_stiff'], ['check_band_wear'],
    ['glute-bridge', 'side-plank', 'lateral-lunge']),

  /* ------------------------------------------------------------------- cardio */
  s('stationary-bike-steady', 'cardio', ['full_body'], ['quads', 'calves'], ['bike'], 'beginner',
    ['adjust_saddle_height', 'steady_cadence', 'conversational_pace'], ['saddle_too_low', 'gripping_too_tight'], ['adjust_seat_first'],
    ['brisk-walk', 'rowing-machine-steady', 'treadmill-walk-incline']),
  s('stationary-bike-intervals', 'cardio', ['full_body'], ['quads', 'glutes'], ['bike'], 'intermediate',
    ['warm_up_first', 'hard_effort_then_easy', 'finish_with_easy_spin'], ['skipping_the_warm_up', 'intervals_too_long'], ['build_intensity_gradually'],
    ['rowing-machine-intervals', 'treadmill-run-intervals', 'jumping-jacks']),
  s('treadmill-walk-incline', 'cardio', ['full_body'], ['glutes', 'calves'], ['treadmill'], 'beginner',
    ['no_holding_the_rails', 'upright_posture', 'steady_breathing'], ['leaning_on_the_handles', 'incline_too_steep_too_soon'], ['use_the_safety_clip'],
    ['brisk-walk', 'stationary-bike-steady', 'stair-climb']),
  s('treadmill-run-intervals', 'cardio', ['full_body'], ['quads', 'calves'], ['treadmill'], 'intermediate',
    ['warm_up_first', 'step_on_at_speed', 'cool_down_walking'], ['skipping_the_warm_up', 'jumping_on_at_full_speed'], ['use_the_safety_clip'],
    ['stationary-bike-intervals', 'rowing-machine-intervals', 'high-knees']),
  s('rowing-machine-steady', 'cardio', ['full_body'], ['back', 'quads', 'lats'], ['rower'], 'beginner',
    ['legs_then_hips_then_arms', 'flat_back', 'steady_rate'], ['pulling_with_arms_first', 'rounding_the_back'], ['set_footstraps_first'],
    ['stationary-bike-steady', 'brisk-walk', 'treadmill-walk-incline']),
  s('rowing-machine-intervals', 'cardio', ['full_body'], ['back', 'quads', 'glutes'], ['rower'], 'intermediate',
    ['warm_up_first', 'drive_with_the_legs', 'easy_recovery_strokes'], ['rushing_the_recovery', 'rounding_the_back'], ['build_intensity_gradually'],
    ['stationary-bike-intervals', 'treadmill-run-intervals', 'burpee']),
  s('jumping-jacks', 'cardio', ['full_body'], ['shoulders', 'calves'], ['none'], 'beginner',
    ['soft_knees', 'full_arm_range', 'steady_rhythm'], ['landing_stiff', 'half_range'], ['land_on_soft_surface'],
    ['high-knees', 'jump-rope', 'mountain-climber']),
  s('high-knees', 'cardio', ['full_body'], ['quads', 'abs', 'calves'], ['none'], 'beginner',
    ['knees_to_hip_height', 'stay_on_the_balls_of_feet', 'arms_driving'], ['leaning_back', 'low_knees'], ['land_on_soft_surface'],
    ['jumping-jacks', 'mountain-climber', 'jump-rope']),
  s('jump-rope', 'cardio', ['full_body'], ['calves', 'forearms'], ['none'], 'intermediate',
    ['small_jumps', 'wrists_do_the_work', 'stay_relaxed'], ['jumping_too_high', 'using_the_whole_arm'], ['land_on_soft_surface'],
    ['jumping-jacks', 'high-knees', 'stationary-bike-steady']),
  s('burpee', 'cardio', ['full_body'], ['chest', 'quads', 'abs'], ['none'], 'intermediate',
    ['step_back_to_regress', 'chest_to_floor_optional', 'stand_fully_each_rep'], ['sagging_hips_on_the_push_up', 'rushing_and_losing_form'], ['step_instead_of_jump_if_needed'],
    ['jump-squat', 'mountain-climber', 'jumping-jacks']),
  s('brisk-walk', 'cardio', ['full_body'], ['calves', 'glutes'], ['none'], 'beginner',
    ['upright_posture', 'brisk_but_conversational', 'consistent_duration'], ['pace_too_slow_to_count', 'skipping_footwear'], ['choose_a_safe_route'],
    ['treadmill-walk-incline', 'stair-climb', 'stationary-bike-steady']),
  s('stair-climb', 'cardio', ['full_body'], ['quads', 'glutes', 'calves'], ['none'], 'beginner',
    ['whole_foot_on_step', 'upright_posture', 'use_the_rail_going_down'], ['skipping_steps_when_tired', 'rushing_the_descent'], ['use_the_rail_if_unsteady'],
    ['brisk-walk', 'treadmill-walk-incline', 'high-knees']),
];

/* ------------------------------------------------------------------- índices */

const BY_SLUG: ReadonlyMap<string, Exercise> = new Map(EXERCISES.map((e) => [e.slug, e]));

/** Devuelve el ejercicio con ese slug, o `undefined` si no existe. */
export function getExercise(slug: string): Exercise | undefined {
  return BY_SLUG.get(slug);
}

/** Igual que `getExercise` pero lanza: úsalo solo con slugs de la propia biblioteca. */
export function getExerciseOrThrow(slug: string): Exercise {
  const found = BY_SLUG.get(slug);
  if (!found) throw new Error(`Ejercicio desconocido: ${slug}`);
  return found;
}

/** Todos los ejercicios de un patrón de movimiento, en el orden del catálogo. */
export function byPattern(pattern: MovementPattern): Exercise[] {
  return EXERCISES.filter((e) => e.pattern === pattern);
}

/** true si el equipo disponible cubre todo lo que pide el ejercicio. */
export function canPerform(exercise: Exercise, equipment: Equipment[]): boolean {
  const owned = new Set<Equipment>(equipment);
  return exercise.equipment.every((needed) => needed === 'none' || owned.has(needed));
}

/** Ejercicios realizables con el equipo disponible. `[]` o `['none']` = solo peso corporal. */
export function availableWith(equipment: Equipment[]): Exercise[] {
  return EXERCISES.filter((e) => canPerform(e, equipment));
}

/** Ejercicios que trabajan ese músculo como primario o secundario. */
export function byMuscle(muscle: MuscleGroup): Exercise[] {
  return EXERCISES.filter(
    (e) => e.primaryMuscles.includes(muscle) || e.secondaryMuscles.includes(muscle),
  );
}

/** Orden de dificultad, útil para filtrar por experiencia. */
export const DIFFICULTY_RANK: Record<Difficulty, number> = {
  beginner: 0,
  intermediate: 1,
  advanced: 2,
};
